name: Deploy to ECS

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        default: staging
  push:
    branches: main

jobs:
  call-workflow:
    uses: mbta/workflows/.github/workflows/deploy-ecs.yml@main
    with:
      app-name: subwayside-ui
      environment: ${{ github.event.inputs.environment || 'staging' }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      docker-repo: ${{ secrets.DOCKER_REPO }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
